### PR TITLE
MNT: rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #4.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

### CODE REVIEW

**Comment by scopatz** [comment]
ping @conda-forge/simple-salesforce!

**Comment by costrouc** [comment]
@scopatz it doesn't look like this triggered python 3.7 builds? I am looking at https://anaconda.org/conda-forge/simple-salesforce/files

**Comment by scopatz** [comment]
It is `noarch: python`. It doesn't need python 3.7 builds per se

**Comment by scopatz** [comment]
@conda-forge-admin please rerender

**Pull request merged**
